### ISSUE TITLE
Treat "function" the same as other keywords

### ISSUE THREAD

**Issue by reyawn** [pebble/eslint-config-pebble#1]
I propose modifying the "space-before-function-paren" setting with the below config:

```
{"anonymous": "always", "named": "never"}
```

This allows `function` to be treated the same as other keywords (like `if`):

``` javascript
if (somethingIsTrue) {
  someFunction(someVar, function () {
    doSomethingElse();
  }
}
```

**Comment by aheckmann** [comment]
it creates inconsistency in anonymous generator fns:

``` js
function *() {

}
```

i've tried :(

**Comment by aheckmann** [comment]
once eslint gets a little better (or we patch it), we can revisit

**Comment by reyawn** [comment]
oh no :(  that makes sense, you did try a bunch of things but the generators were causing problems.
